export const SHAKE_THE_TREE = 'SHAKE_THE_TREE';
export const STOP_THE_TREE = 'STOP_THE_TREE';

export const DROP_THE_APPLES = 'DROP_THE_APPLES';
export const COLLECT_THE_APPLES = 'COLLECT_THE_APPLES';
